### ISSUE TITLE
File corrupted

### ISSUE THREAD

**Issue by maxgorky** [DanielRuf/ninjafirewall-config-browser#7]
Hi Daniel!

I was trying to upload the file but it failed with NinjaFirewall saying it's corrupted or something. Is the file still working?

Thank you!

**Comment by DanielRuf** [comment]
The file generation should still be working.

What browser do you use?

**Comment by DanielRuf** [comment]
Works for me with NinjaFirewal WP Edition 4.3.2

<img width="288" alt="Bildschirmfoto 2021-04-04 um 01 39 44" src="https://user-images.githubusercontent.com/827205/113494226-b8474700-94e6-11eb-9d4f-05adb1156351.png">

**Comment by DanielRuf** [comment]
Works for me with NinjaFirewall WP Edition 4.3.2

<img width="288" alt="Bildschirmfoto 2021-04-04 um 01 39 44" src="https://user-images.githubusercontent.com/827205/113494226-b8474700-94e6-11eb-9d4f-05adb1156351.png">

**Comment by maxgorky** [comment]
All good mate, my bad. I just downlaoded that ZIP file by mistake, should have downloaded .dat file. Sorry for confusion! 
Looks like no issues at the moment:) Would you recommend any other additional settings on top of those ones?

**Comment by DanielRuf** [comment]
It depends (on the website, attack surface and the specific case).

You can enable a few more restrictions in the policies and options section (for example you can often disable the plugins and themes file editor feature). And there are also the security header options (Frame Options should not be set to sameorigin if parts of your website are allowed to be includedon other websites via iframes).

The provided configuration is not too strict to prevent issues in some more common setups like shops.

Besides the available options and policies you can extend NinjaFirewall through a .htninja file (I have one which implements logging for the BLOCK rules there too).

Closing as the initial issue is resolved. Thanks for the feedback that it works now.
